stages:
  - lint
  - test
  - build
linter:
  stage: lint
  image: python:latest
  before_script:
    - pip install cpplint
  script:
    - make lint
unit_tests:
  stage: test
  image: gcc:latest
  script:
    - make build_test
    - make run_test
  artifacts:
    expire_in: 1 day
    paths:
      - test/build/pwire-sensor-test
build_prod:
  stage: build
  image: curlimages/curl:latest
  only:
    - master
  before_script:
    - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
    - ls .
    - export PATH=$PATH:/builds/project-0/bin
    - arduino-cli core update-index --config-file arduino-cli.yml
    - arduino-cli core install esp8266:esp8266 --config-file arduino-cli.yml
#    - arduino-cli board listall -- To list all possibilities
  script:
    - arduino-cli compile --fqbn esp8266:esp8266:d1_mini exe/src/Blink.ino
    - arduino-cli help lib
    - ls
#    - make build_lib_prod
#    - make build_prod
  artifacts:
    expire_in: 14 days
    paths:
      - exe/build/pwire-server