stages:
  - lint
  - test
  - build
linter:
  stage: lint
  image: python:latest
  before_script:
    - pip install cpplint
  script:
    - make lint
unit_tests:
  stage: test
  image: gcc:latest
  before_script:
    - apt update
    - apt install python-pip -y
    - pip install gcovr
  script:
    - make build_test
    - make run_test
  artifacts:
    expire_in: 1 day
    paths:
      - test/build/pwire-sensor-test
build_prod:
  stage: build
  image: gitlab.dev.ifs.hsr.ch:45023/epj/2020/pwire/pwire-sensor:exe
  only:
    - master
  before_script:
    - git clone https://github.com/xreef/LoRa_E32_Series_Library.git lib/build/LoRa_E32_Series_Library
  script:
    - make build_prod
  artifacts:
    expire_in: 14 days
    paths:
      - exe/build/