stages:
  - lint
  - test
  - build
linter:
  stage: lint
  image: python:latest
  before_script:
    - pip install cpplint
  script:
    - make lint
unit_tests:
  stage: test
  image: gcc:latest
  script:
    - make build_test
    - make run_test
  artifacts:
    expire_in: 1 day
    paths:
      - test/build/pwire-sensor-test
build_prod:
  stage: build
  image: debian:latest #alpine:latest
  only:
    - master
  before_script:
#    - apk add make curl
    - apt update
    - apt install make curl -y
    - make prepare
  script:
    - ls -al /root/.arduino15/packages/esp8266/tools/
    - make build_prod
  artifacts:
    expire_in: 14 days
    paths:
      - exe/build/